name: rnb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.2.0
  flutter_neumorphic: ^3.0.0
  im_stepper: ^0.1.3
  date_time_picker: ^2.0.0
  select_form_field: ^2.0.0
  fluttertoast: ^8.0.7
  image_picker: ^0.8.0+3
  firebase_auth: ^3.3.18
  firebase_core: ^1.3.0
  shared_preferences: ^2.0.6
  flutter_datetime_picker: ^1.5.1
  floating_action_bubble: ^1.1.2
  font_awesome_flutter: ^10.1.0
  image_cropper: ^2.0.3
  path_provider: ^2.0.2
  pdf_viewer_flutter: ^1.0.2
#  flutter_full_pdf_viewer: ^1.0.6
  pdf: ^3.4.2
  share_extend: ^2.0.0
  progress_dialog: ^1.2.4
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true



  assets:
    - images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf


